# ============================================================
# FILE PATH:  recalla-backend/setup_google_oauth.py
# PURPOSE:    One-time setup. Run this ONCE to grant Recalla access
#             to your Google Calendar + Gmail.
#             Saves refresh token to .env for permanent backend use.
#
# USAGE:      python setup_google_oauth.py
# ============================================================

"""
One-time Google OAuth setup for Recalla.

Steps:
1. Make sure credentials.json is in this folder (downloaded from Google Cloud)
2. Run: python setup_google_oauth.py
3. Browser opens — sign in with your Gmail and grant permissions
4. Script saves refresh token to .env
5. Done — backend will use this forever
"""

import os
import json
from pathlib import Path

# Required Google API scopes
SCOPES = [
    "https://www.googleapis.com/auth/calendar",       # Full Calendar access
    "https://www.googleapis.com/auth/gmail.modify",   # Read, draft, send Gmail
]

CREDS_FILE  = "credentials.json"
TOKEN_FILE  = "token.json"
ENV_FILE    = ".env"


def main():
    print("\n" + "="*60)
    print("  Recalla — Google OAuth Setup")
    print("="*60 + "\n")

    # Check credentials.json exists
    if not os.path.exists(CREDS_FILE):
        print(f"ERROR: {CREDS_FILE} not found in this folder.")
        print("\nDownload it from Google Cloud Console:")
        print("  → APIs & Services → Credentials → your OAuth client → Download JSON")
        print(f"  → Save it here as: {CREDS_FILE}\n")
        return

    # Import here so the script can show a friendlier error if libs are missing
    try:
        from google_auth_oauthlib.flow import InstalledAppFlow
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
    except ImportError:
        print("ERROR: Google libraries not installed. Run:\n")
        print("  pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client\n")
        return

    creds = None

    # Check if token.json exists (already authorized before)
    if os.path.exists(TOKEN_FILE):
        print(f"[i] Found existing {TOKEN_FILE}, validating...")
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

    # If no valid creds, do the OAuth flow
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            print("[i] Refreshing expired token...")
            creds.refresh(Request())
        else:
            print("[i] Starting OAuth flow — your browser will open in a moment.")
            print("[i] Sign in with the Gmail account you want Recalla to use.\n")
            flow = InstalledAppFlow.from_client_secrets_file(CREDS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)

        # Save token for next time
        with open(TOKEN_FILE, "w") as f:
            f.write(creds.to_json())
        print(f"[✓] Token saved to {TOKEN_FILE}")

    # Load client info from credentials.json
    with open(CREDS_FILE) as f:
        client_data = json.load(f)
    client_info = client_data.get("installed") or client_data.get("web") or {}
    client_id     = client_info.get("client_id", "")
    client_secret = client_info.get("client_secret", "")

    # Show what we got
    print("\n" + "="*60)
    print("  SUCCESS — Google account connected")
    print("="*60)
    print(f"  Client ID:     {client_id[:30]}...")
    print(f"  Refresh token: {creds.refresh_token[:30]}...")
    print()

    # Append to .env if not already there
    env_path = Path(ENV_FILE)
    existing = env_path.read_text() if env_path.exists() else ""

    # Clean out any old Google entries
    new_lines = []
    for line in existing.splitlines():
        if not any(line.startswith(k) for k in ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"]):
            new_lines.append(line)
    new_lines.append("")
    new_lines.append("# Google OAuth (auto-generated by setup_google_oauth.py)")
    new_lines.append(f"GOOGLE_CLIENT_ID={client_id}")
    new_lines.append(f"GOOGLE_CLIENT_SECRET={client_secret}")
    new_lines.append(f"GOOGLE_REFRESH_TOKEN={creds.refresh_token}")

    env_path.write_text("\n".join(new_lines) + "\n")
    print(f"[✓] Saved to {ENV_FILE}")
    print()

    # Test by listing first 3 calendar events
    print("[i] Testing — fetching your next 3 calendar events...\n")
    try:
        from googleapiclient.discovery import build
        from datetime import datetime, timezone
        service = build("calendar", "v3", credentials=creds)
        events_result = service.events().list(
            calendarId="primary",
            timeMin=datetime.now(timezone.utc).isoformat(),
            maxResults=3,
            singleEvents=True,
            orderBy="startTime",
        ).execute()
        events = events_result.get("items", [])
        if events:
            print("  Your upcoming events:")
            for e in events:
                start = e["start"].get("dateTime", e["start"].get("date", "?"))
                print(f"    · {e.get('summary', '(no title)')} — {start}")
        else:
            print("  No upcoming events found (calendar is empty)")
    except Exception as e:
        print(f"  ⚠ Calendar test failed: {e}")

    # Test Gmail
    print("\n[i] Testing — checking Gmail inbox count...\n")
    try:
        from googleapiclient.discovery import build
        service = build("gmail", "v1", credentials=creds)
        profile = service.users().getProfile(userId="me").execute()
        print(f"  Connected to: {profile.get('emailAddress')}")
        print(f"  Total messages: {profile.get('messagesTotal')}")
    except Exception as e:
        print(f"  ⚠ Gmail test failed: {e}")

    print("\n" + "="*60)
    print("  Setup complete! You can now use Calendar + Email tools.")
    print("="*60 + "\n")


if __name__ == "__main__":
    main()